name: widgets_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  go_router: ^7.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # este .pem es para evitar el error de imagen.network, ver modificaciondel main para usar un certifado
  assets:
    - assets/ca/lets-encrypt-r3.pem
    - assets/images/
